Lib/src/domain/Student.java
Lib/src/domain/Subject.java

Files that included are the class that holds the data of student and subject

Add domain

---

Lib/src/repository/CRUDStudent.java
Lib/src/repository/CRUDSubject.java

Files that included are the file that interact with the database, CRUDStudent and CRUDSubject.

Add initial repository

---

Lib/src/gui/FrameMain.java

Initialize the jbutton of grades and components

Update MainFrame Version 1.1

---

Lib/src/gui/entity/subject/DialogUpdateSubject.java

Add DialogUpdateSubject.java (Update Dialog)

---

Lib/src/EMarkaApplication.java
Lib/src/gui/FrameMain.java

Update Gui EMarkaApp and Framework to connect everything

GUI Finalization

---

Lib/src/gui/entity/component/TemplateWW.java

add templateWW.java

---

Lib/src/sample.java

Revert "this is a sample program"

---

Lib/src/repository/CRUDPerformanceTasks.java
Lib/src/repository/CRUDQuarterlyAssessment.java
Lib/src/repository/CRUDWrittenWorks.java

will have zero grade to have no error in the Grade Table Model.

New changes. Once a component is added, all students under that subject

---

Lib/src/gui/entity/grade/PanelGradeManagement.java
Lib/src/gui/entity/grade/TemplateGrade.java

zero grades reflect in the Grade Management Panel without error

gradeHotfix

---

Lib/src/gui/entity/grade/DialogViewGrade.java
Lib/src/gui/entity/grade/PanelGradeManagement.java
Lib/src/gui/entity/grade/TemplateGrade.java

Enhance and debug GUI Grade

---

Lib/src/domain/Grade.java
Lib/src/repository/CRUDGrade.java

Fix the compatibility and the words

Enhance Grade and CRUDGrade

---

Lib/src/repository/CRUDGrade.java
Lib/src/repository/CRUDPerformanceTasks.java
Lib/src/repository/CRUDQuarterlyAssessment.java
Lib/src/repository/CRUDWrittenWorks.java

Improve getAll() of components and Improve Debug CRUDGrade.java

Enhance Repository

---

Lib/src/domain/Grade.java
Lib/src/gui/entity/grade/DialogViewGrade.java
Lib/src/gui/entity/grade/PanelGradeManagement.java

Update Grade Class and Update DialogViewGrade.java and add it to the Panel

Enhance Grade Function

---

Lib/src/gui/entity/grade/DialogViewGrade.java
Lib/src/gui/entity/grade/PanelGradeManagement.java
Lib/src/repository/CRUDGrade.java

Editable Grade in Dialog and improve the connectivity in the panel and hotfix CRUDGrade.java

Enhancement of Grade Function

---

Lib/src/EMarkaApplication.java
Lib/src/gui/FrameMain.java
Lib/src/gui/entry/LogIn.java

New login function. Changes in main entry point and main frame to make
the login work.

LOGIN FUNCTIONS

---

Lib/src/gui/entity/grade/DialogViewGrade.java

Updated to refresh the table and have the grade viewed Problem: No name yet in dialog

Enhance DialogViewGrade

---

Lib/src/gui/entity/grade/DialogViewGrade.java
Lib/src/gui/entity/grade/PanelGradeManagement.java

- can now see Name of specific student
- can now see Total of each component for reference of instructor when
inputting grades
- enhancement of View Dialog Design GUI Design to make it more
user-friendly

enhancement of View Grade

---

Lib/src/gui/FrameMain.java
Lib/src/gui/PanelWelcome.java

- enhancement of design of Main Frame GUI to make it more appealing to
the eyes
- linked new Welcome Panel - whenever login is successful, the Welcome
Panel shall be first to appear in the Main Frame

Enhancement of Main Frame + New Welcome Panel

---

Lib/src/gui/entity/grade/DialogViewGrade.java

Update the computation of grade and grade be 2 decimals

 Enhance of Dialog

---

Lib/src/gui/FrameMain.java
Lib/src/gui/entity/grade/DialogViewGrade.java

Improve the refresh rate of the frame and fix some bug in grade Dialog

Hotfix Frame And Grade Dialog

---

Lib/src/gui/entity/grade/DialogViewGrade.java

Minimum grade should be 60. Maximum grade should be 99.

Hotfix in Grade Computation

---

Lib/src/gui/entity/subject/DialogCreateSubject.java
Lib/src/gui/entity/subject/PanelSubjectManagement.java

Deleted "Update" and "Delete Subject" buttons
Configured size of dialog

Hotfix of Subject Dialog and Subject Panel Mgmt

---

Lib/src/gui/entity/student/PanelStudentManagement.java
Lib/src/gui/entity/student/TemplateStudent.java
Lib/src/repository/CRUDStudent.java

Enhanced student repository, panel and table model so that students are
now arranged in alphabetical order

Students now in alphabetical order

---

Lib/src/gui/entity/grade/DialogViewGrade.java
Lib/src/gui/entity/grade/PanelGradeManagement.java
Lib/src/repository/CRUDGrade.java

* Students name in format "LN, FN MN" instead of "FN LN"
* Design enhancement such as font colors, sizes etc.

Enhancement of design in Grades

---

Lib/src/gui/FrameMain.java
Lib/src/gui/PanelWelcome.java
Lib/src/gui/entity/component/PanelComponentPT.java
Lib/src/gui/entity/component/PanelComponentQA.java
Lib/src/gui/entity/component/PanelComponentWW.java
Lib/src/gui/entity/subject/PanelSubjectManagement.java
Lib/src/gui/entry/LogIn.java

* Major changes in GUI design (font size, colors etc.) to make it more
appealing to the eyes of the end-user (due to bland colors such as gray)
* Changes in names, titles, labels (e.g from WW Panel to List of Written
Works) for formality and user-friendliness

Revamp (restart) of GUI design

---

Lib/src/gui/entity/grade/DialogViewGrade.java
Lib/src/gui/entity/grade/PanelGradeManagement.java

Enhance Gui so it didnt close and also update the computed grade

finalization of Dialog Grade

---

Lib/src/gui/FrameMain.java
Lib/src/gui/entity/component/PanelComponentPT.java
Lib/src/gui/entity/component/PanelComponentQA.java
Lib/src/gui/entity/component/PanelComponentWW.java
Lib/src/gui/entity/grade/PanelGradeManagement.java
Lib/src/gui/entity/student/PanelStudentManagement.java

Added "refreshPanel()" method so that whenever a panel button is
clicked, it will immediately refresh.

Enhancement of Panel to Refresh Immediately

---

Lib/src/gui/entity/grade/DialogViewGrade.java
Lib/src/repository/CRUDPerformanceTasks.java
Lib/src/repository/CRUDQuarterlyAssessment.java

Hotfixed Repository of PT and QA so that it will not return a
NullPointerException

Hotfix Grade Repo

---

Lib/src/gui/entity/student/PanelStudentManagement.java
Lib/src/gui/entity/subject/DialogCreateSubject.java

* Removed Delete function in Student Panel because of SQL Constraint
Violation
* Hotfixed symbol of Success dialog when subject is saved (from "?" to
"i")

Last hotfixes before submissions
